
services:
  service-api:
    build:
      context: ../../Downloads/SnoozBackendApis-master
      dockerfile: ../../Downloads/SnoozBackendApis-master/docker/api.dev.Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - API_PORT=8080
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
    depends_on:
      - postgres
    networks:
      - api-network
    volumes:
      - .:/app

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - api_postgres:/var/lib/postgresql/data
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

volumes:
  api_postgres: {}