
services:
  service-api:
    build:
      context: ../../Downloads/SnoozBackendApis-master
      dockerfile: ../../Downloads/SnoozBackendApis-master/docker/service-api.dev.Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - SERVICE_API_PORT=8080
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
    depends_on:
      - redis
      - postgres
    networks:
      - snooz-network
    volumes:
      - .:/app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - snooz-network

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - snooz_backend:/var/lib/postgresql/data
    networks:
      - snooz-network

networks:
  snooz-network:
    driver: bridge

volumes:
  snooz_backend: {}